import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import localFont from 'next/font/local'
import { Toaster } from "react-hot-toast";
const sahelFont = localFont({
  src: '../font/Sahel.woff',
  variable: '--sahel-font',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${sahelFont.variable} bg-stone-50`}
      >
        <Header />
        <NextUIProvider>
          {children}
        </NextUIProvider>
        <Toaster toastOptions={{ style: { direction: "ltr" } }} />
        <Footer />
      </body>
    </html>
  );
}
